/**
 * fm_sine_rom.v
 * FOUNDATION: Milestone 2.2
 * 
 * A 1024-entry 16-bit signed Sine Lookup Table (ROM).
 * Initialized from sine_lut.mem generated by software/generate_sine_lut.py.
 */

module fm_sine_rom #(
    parameter ADDR_WIDTH = 10,
    parameter DATA_WIDTH = 16,
    parameter MEM_FILE = "rtl/sine_lut.mem"
)(
    input  wire                  clk,
    input  wire [ADDR_WIDTH-1:0] addr,
    output reg  [DATA_WIDTH-1:0] data_out
);

    // Distributed RAM / ROM
    reg [DATA_WIDTH-1:0] rom [0:(2**ADDR_WIDTH)-1];

    // Load LUT values at configuration
    initial begin
        $readmemh(MEM_FILE, rom);
    end

    // Synchronous read (best for FPGA BRAM inference)
    always @(posedge clk) begin
        data_out <= rom[addr];
    end

endmodule
