import numpy as np
import os

def generate_sine_lut(size=1024, bit_depth=16, output_path="rtl/sine_lut.mem"):
    """
    Generates a 1024-entry 16-bit signed Sine Lookup Table.
    Values are scaled to use the full range of a 16-bit signed integer (-32768 to 32767).
    """
    # 1. Generate one cycle of a sine wave
    # indices from 0 to size-1
    indices = np.arange(size)
    sine_values = np.sin(2 * np.pi * indices / size)
    
    # 2. Scale to bit depth
    # Max positive value for 16-bit signed is 32767
    scale = (2**(bit_depth - 1)) - 1
    scaled_sine = np.round(sine_values * scale).astype(np.int16)
    
    # 3. Export to Verilog hex format (.mem)
    # We use 4 hex digits for 16 bits
    with open(output_path, "w") as f:
        f.write(f"// 1024-entry 16-bit signed Sine LUT\n")
        f.write(f"// Generated by generate_sine_lut.py\n")
        for val in scaled_sine:
            # Convert signed to 16-bit hex (handle negative numbers)
            # & 0xFFFF ensures we get the unsigned representation for hex display
            hex_val = hex(val & 0xFFFF)[2:].zfill(4)
            f.write(f"{hex_val}\n")
            
    print(f"Sine LUT generated: {output_path}")
    print(f"Max: {np.max(scaled_sine)}, Min: {np.min(scaled_sine)}")
    return scaled_sine

if __name__ == "__main__":
    if not os.path.exists("rtl"):
        os.makedirs("rtl")
    generate_sine_lut()
